
# Name and description of site.
# Used in _layouts/default.html.
#  - The first is also used in metadata, and so cannot include markup.
#
# URL is used in "Sitemap.xml" and RSS feed.
#
name:        GenomeArk
description: Genome Data from the                                           Earth BioGenome Project,                                                     Vertebrate Genomes Project,                                                                      Telomere-to-Telomere Consortium     and others.
descriphtml: Genome Data from the <a href="https://www.earthbiogenome.org/">Earth BioGenome Project</a>, <a href="https://vertebrategenomesproject.org/">Vertebrate Genomes Project</a>, <a href="https://sites.google.com/ucsc.edu/t2tworkinggroup/home">Telomere-to-Telomere Consortium</a> and others.
url:         https://genomeark.github.io

footer-links:
  github: genomeark/genomeark.github.io
  twitter: genomeark
  email:

source:           .
destination:      ./_site

plugins_dir:      _plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

layouts_dir:      _layouts
data_dir:         _data
includes_dir:     _includes

sass:
  sass_dir:       _sass
  style:          :expanded     # You might prefer to minify using :compressed

#  Don't include this crud in the _site.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - README.txt
  - CNAME
  - _layouts/.#genomeark.html

# Jekyll 3 now only supports Kramdown for Markdown.
#   Use GitHub flavored markdown, including triple backtick fenced code blocks
#   Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
#   Use existing pygments syntax highlighting css
#
#  I can't get highlighting to do anything....
#
kramdown:
  input: GFM
  syntax_highlighter: rouge

#  syntax_highlighter_opts:
#    css_class: 'highlight'

# Markdown Processors (from defaults page)
#kramdown:
#  auto_ids          : true
#  entity_output     : as_char
#  toc_levels        : [1, 2, 3, 4, 5, 6]
#  smart_quotes      : lsquo,rsquo,ldquo,rdquo
#  input             : GFM
#  hard_wrap         : false
#  footnote_nr       : 1
#  show_warnings     : false





#
#  GenomeArk pages
#

collections:
  genomeark-all:
    output: true
  genomeark-curated-assembly:
    output: true
  genomeark-draft-assembly:
    output: true
  genomeark-raw-data-only:
    output: true

  vgp-all:
    output: true
  vgp-curated-assembly:
    output: true
  vgp-draft-assembly:
    output: true
  vgp-raw-data-only:
    output: true

  t2t-all:
    output: true
  t2t-curated-assembly:
    output: true
  t2t-draft-assembly:
    output: true
  t2t-raw-data-only:
    output: true


defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

  - scope:
      path: "_genomeark-all"
    values:
      layout: genomeark
      use_name_for_title: true
  - scope:
      path: "_genomeark-curated-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  - scope:
      path: "_genomeark-draft-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  - scope:
      path: "_genomeark-raw-data-only"
    values:
      layout: genomeark
      use_name_for_title: true

  - scope:
      path: "_vgp-all"
    values:
      layout: genomeark
      use_name_for_title: true
  - scope:
      path: "_vgp-curated-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  - scope:
      path: "_vgp-draft-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  - scope:
      path: "_vgp-raw-data-only"
    values:
      layout: genomeark
      use_name_for_title: true

  - scope:
      path: "_t2t-all"
    values:
      layout: genomeark
      use_name_for_title: true
  - scope:
      path: "_t2t-curated-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  - scope:
      path: "_t2t-draft-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  - scope:
      path: "_t2t-raw-data-only"
    values:
      layout: genomeark
      use_name_for_title: true
