#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: GenomeArk

# Short bio or description (displayed in the header)
# The first is also used in metadata, and so cannot include markup.
# Used in _layouts/default.html.
description: Genome Data from the                                           Earth BioGenome Project,                                                     Vertebrate Genomes Project,                                                                      Telomere-to-Telomere Consortium     and others.
descriphtml: Genome Data from the <a href="https://www.earthbiogenome.org/">Earth BioGenome Project</a>, <a href="https://vertebrategenomesproject.org/">Vertebrate Genomes Project</a>, <a href="https://sites.google.com/ucsc.edu/t2tworkinggroup/home">Telomere-to-Telomere Consortium</a> and others.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/images/vgp.png

# used in blog posts to denote the end of the excerpt used for lists
excerpt_separator: "<!--excerpt-->"

paginate: 6
paginate_path: "/news/page:num/"

collections:
  genomeark-all:
    output: true
  genomeark-curated-assembly:
    output: true
  genomeark-draft-assembly:
    output: true
  genomeark-raw-data-only:
    output: true

  vgp-all:
    output: true
  vgp-curated-assembly:
    output: true
  vgp-draft-assembly:
    output: true
  vgp-raw-data-only:
    output: true

  t2t-all:
    output: true
  t2t-curated-assembly:
    output: true
  t2t-draft-assembly:
    output: true
  t2t-raw-data-only:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      comments: false
  -
    scope:
      path: "_genomeark-all"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_genomeark-curated-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_genomeark-draft-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_genomeark-raw-data-only"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_vgp-all"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_vgp-curated-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_vgp-draft-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_vgp-raw-data-only"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_t2t-all"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_t2t-curated-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_t2t-draft-assembly"
    values:
      layout: genomeark
      use_name_for_title: true
  -
    scope:
      path: "_t2t-raw-data-only"
    values:
      layout: genomeark
      use_name_for_title: true



#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: genomeark/genomeark.github.io
  instagram:
  linkedin:
  pinterest:
  rss: # uncomment and put something here to enable
  twitter: genomeark
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

grepository: vgp

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: vgp

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://vgp.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - README.txt
  - CNAME
  - _layouts/.#genomeark.html
